- hosts: all
  name: copy html file
  become: true
  tasks:
    - name: copy file
      copy:
        src: /var/lib/jenkins/workspace/ansible-jenkins1/index.html
        dest: /var/www/html/index.html
